export const MIN_TEST_CASES_ERROR = '1 IS MIN NUMBER OF TEST CASES';
export const MAX_TEST_CASES_ERROR = '1000 IS MAX NUMBER OF TEST CASES';
export const VALID_INTEGER_ERROR = 'PLEASE ENTER VALID INTEGER';
export const NUMBER_OF_SPACES = 'PLEASE ENTER ONLY ONE SPACE BETWEEN NUMBERS';
export const NUMBER_OF_INTEGERS = 'PLEASE ENTER APPROPRIATE NUMBER OF INTEGERS';
export const NUMBER_OF_WHITE_PIXEL = 'PLEASE ENTER AT LEAST ONE WHITE PIXEL'
  